apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dso-demo
  name: dso-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dso-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'dso-demo'
        vault.hashicorp.com/agent-inject-secret-database: 'secret/dso-demo/database'
        vault.hashicorp.com/agent-inject-template-database: |
          {{- with secret "secret/dso-demo/database" -}}
            mysql -u {{ .Data.data.username }} -p {{ .Data.data.password }} -h database:3306 mydb
          {{- end -}}
      labels:
        app: dso-demo
    spec:
      #automountServiceAccountToken: false # allow vault to add tokens
      serviceAccountName: dso-demo
      containers:
      - image: mikejonesey/dso-demo
        name: dso-demo
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: tmp
            mountPath: /tmp
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        securityContext:
          capabilities:
            drop:
              - ALL
          privileged: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 10001
          runAsGroup: 10001
          readOnlyRootFilesystem: true
      volumes:
        - name: tmp
          emptyDir: {}
status: {}
